var R=require("../../../chunks/[turbopack]_runtime.js")("server/app/(frontend)/feed.xml/route.js")
R.c("server/chunks/[root-of-the-server]__1x278cj._.js")
R.c("server/chunks/_15lrz12._.js")
R.c("server/chunks/_0zvlmmz._.js")
R.c("server/chunks/[root-of-the-server]__0v_wsvf._.js")
R.c("server/chunks/_0847jrf._.js")
R.c("server/chunks/[root-of-the-server]__12uj088._.js")
R.c("server/chunks/_1ntdu-6._.js")
R.c("server/chunks/node_modules_next_dist_17t41mm._.js")
R.c("server/chunks/node_modules_next_dist_compiled_06q7exl._.js")
R.c("server/chunks/_next-internal_server_app_(frontend)_feed_xml_route_actions_1e4ykqg.js")
R.m(466040)
module.exports=R.m(466040).exports
