var R=require("../../../../../chunks/[turbopack]_runtime.js")("server/app/(frontend)/api/layouts/[id]/route.js")
R.c("server/chunks/[root-of-the-server]__189ic2b._.js")
R.c("server/chunks/_0ejz1x6._.js")
R.c("server/chunks/node_modules_next_dist_compiled_06q7exl._.js")
R.c("server/chunks/[root-of-the-server]__12uj088._.js")
R.c("server/chunks/[root-of-the-server]__0v_wsvf._.js")
R.c("server/chunks/node_modules_next_dist_17t41mm._.js")
R.c("server/chunks/_0zvlmmz._.js")
R.c("server/chunks/_0847jrf._.js")
R.c("server/chunks/_1ntdu-6._.js")
R.c("server/chunks/node_modules_next_dist_0asya_d._.js")
R.c("server/chunks/node_modules_next_1lo724y._.js")
R.c("server/chunks/_next-internal_server_app_(frontend)_api_layouts_[id]_route_actions_1ct3q85.js")
R.m(385474)
module.exports=R.m(385474).exports
