var R=require("../../../../../../chunks/[turbopack]_runtime.js")("server/app/(frontend)/api/admin/audience/command-center/route.js")
R.c("server/chunks/[root-of-the-server]__1v550hc._.js")
R.c("server/chunks/[root-of-the-server]__0v_wsvf._.js")
R.c("server/chunks/node_modules_next_dist_compiled_06q7exl._.js")
R.c("server/chunks/_1c7u-2l._.js")
R.c("server/chunks/node_modules_next_1lo724y._.js")
R.c("server/chunks/[root-of-the-server]__12uj088._.js")
R.c("server/chunks/_0zvlmmz._.js")
R.c("server/chunks/node_modules_next_dist_17t41mm._.js")
R.c("server/chunks/_0k60ylq._.js")
R.c("server/chunks/_1ntdu-6._.js")
R.c("server/chunks/node_modules_next_dist_0asya_d._.js")
R.c("server/chunks/1oeh_server_app_(frontend)_api_admin_audience_command-center_route_actions_121h_np.js")
R.m(583562)
module.exports=R.m(583562).exports
