// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../src/app/(frontend)/[...path]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[...path]">> = Specific
  const handler = {} as typeof import("../../src/app/(frontend)/[...path]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(frontend)/admin/audience/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/audience">> = Specific
  const handler = {} as typeof import("../../src/app/(frontend)/admin/audience/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(frontend)/admin/catalog/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/catalog">> = Specific
  const handler = {} as typeof import("../../src/app/(frontend)/admin/catalog/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(frontend)/admin/catalog/preview/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/catalog/preview/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/(frontend)/admin/catalog/preview/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(frontend)/admin/commerce/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/commerce">> = Specific
  const handler = {} as typeof import("../../src/app/(frontend)/admin/commerce/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(frontend)/admin/fulfillment/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/fulfillment">> = Specific
  const handler = {} as typeof import("../../src/app/(frontend)/admin/fulfillment/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(frontend)/admin/migration/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/migration">> = Specific
  const handler = {} as typeof import("../../src/app/(frontend)/admin/migration/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(frontend)/admin/releases/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/releases">> = Specific
  const handler = {} as typeof import("../../src/app/(frontend)/admin/releases/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(frontend)/admin/social/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/social">> = Specific
  const handler = {} as typeof import("../../src/app/(frontend)/admin/social/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(frontend)/admin/workflow/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/workflow">> = Specific
  const handler = {} as typeof import("../../src/app/(frontend)/admin/workflow/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(frontend)/articles/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/articles/[slug]">> = Specific
  const handler = {} as typeof import("../../src/app/(frontend)/articles/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(frontend)/articles/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/articles">> = Specific
  const handler = {} as typeof import("../../src/app/(frontend)/articles/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(frontend)/builder/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/builder/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/(frontend)/builder/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(frontend)/builder/[id]/preview/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/builder/[id]/preview">> = Specific
  const handler = {} as typeof import("../../src/app/(frontend)/builder/[id]/preview/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(frontend)/calendar/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/calendar">> = Specific
  const handler = {} as typeof import("../../src/app/(frontend)/calendar/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(frontend)/cart/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/cart">> = Specific
  const handler = {} as typeof import("../../src/app/(frontend)/cart/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(frontend)/checkout/cancel/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/checkout/cancel">> = Specific
  const handler = {} as typeof import("../../src/app/(frontend)/checkout/cancel/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(frontend)/checkout/return/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/checkout/return">> = Specific
  const handler = {} as typeof import("../../src/app/(frontend)/checkout/return/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(frontend)/checkout/test/[reference]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/checkout/test/[reference]">> = Specific
  const handler = {} as typeof import("../../src/app/(frontend)/checkout/test/[reference]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(frontend)/connections/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/connections">> = Specific
  const handler = {} as typeof import("../../src/app/(frontend)/connections/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(frontend)/donate/[campaignId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/donate/[campaignId]">> = Specific
  const handler = {} as typeof import("../../src/app/(frontend)/donate/[campaignId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(frontend)/donate/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/donate">> = Specific
  const handler = {} as typeof import("../../src/app/(frontend)/donate/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(frontend)/events/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/events">> = Specific
  const handler = {} as typeof import("../../src/app/(frontend)/events/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(frontend)/graphics-studio/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/graphics-studio">> = Specific
  const handler = {} as typeof import("../../src/app/(frontend)/graphics-studio/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(frontend)/guided-setup/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/guided-setup">> = Specific
  const handler = {} as typeof import("../../src/app/(frontend)/guided-setup/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(frontend)/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../src/app/(frontend)/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(frontend)/member-auth/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/member-auth">> = Specific
  const handler = {} as typeof import("../../src/app/(frontend)/member-auth/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(frontend)/member-auth/verify/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/member-auth/verify">> = Specific
  const handler = {} as typeof import("../../src/app/(frontend)/member-auth/verify/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(frontend)/members/[handle]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/members/[handle]">> = Specific
  const handler = {} as typeof import("../../src/app/(frontend)/members/[handle]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(frontend)/members/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/members">> = Specific
  const handler = {} as typeof import("../../src/app/(frontend)/members/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(frontend)/members/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/members/settings">> = Specific
  const handler = {} as typeof import("../../src/app/(frontend)/members/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(frontend)/messages/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/messages">> = Specific
  const handler = {} as typeof import("../../src/app/(frontend)/messages/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(frontend)/network/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/network">> = Specific
  const handler = {} as typeof import("../../src/app/(frontend)/network/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(frontend)/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/(frontend)/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(frontend)/podcasts/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/podcasts/[slug]">> = Specific
  const handler = {} as typeof import("../../src/app/(frontend)/podcasts/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(frontend)/podcasts/episodes/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/podcasts/episodes/[slug]">> = Specific
  const handler = {} as typeof import("../../src/app/(frontend)/podcasts/episodes/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(frontend)/pos/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/pos">> = Specific
  const handler = {} as typeof import("../../src/app/(frontend)/pos/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(frontend)/preferences/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/preferences">> = Specific
  const handler = {} as typeof import("../../src/app/(frontend)/preferences/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(frontend)/preview/article/[token]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/preview/article/[token]">> = Specific
  const handler = {} as typeof import("../../src/app/(frontend)/preview/article/[token]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(frontend)/search/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/search">> = Specific
  const handler = {} as typeof import("../../src/app/(frontend)/search/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(frontend)/setup/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/setup">> = Specific
  const handler = {} as typeof import("../../src/app/(frontend)/setup/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(frontend)/social-studio/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/social-studio">> = Specific
  const handler = {} as typeof import("../../src/app/(frontend)/social-studio/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(frontend)/store/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/store">> = Specific
  const handler = {} as typeof import("../../src/app/(frontend)/store/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(frontend)/subscribe/confirm/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/subscribe/confirm">> = Specific
  const handler = {} as typeof import("../../src/app/(frontend)/subscribe/confirm/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(frontend)/subscribe/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/subscribe">> = Specific
  const handler = {} as typeof import("../../src/app/(frontend)/subscribe/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(frontend)/unsubscribe/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/unsubscribe">> = Specific
  const handler = {} as typeof import("../../src/app/(frontend)/unsubscribe/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(frontend)/videos/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/videos/[slug]">> = Specific
  const handler = {} as typeof import("../../src/app/(frontend)/videos/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(frontend)/videos/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/videos">> = Specific
  const handler = {} as typeof import("../../src/app/(frontend)/videos/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(payload)/admin/[[...segments]]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/[[...segments]]">> = Specific
  const handler = {} as typeof import("../../src/app/(payload)/admin/[[...segments]]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(frontend)/.well-known/nodeinfo/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/.well-known/nodeinfo">> = Specific
  const handler = {} as typeof import("../../src/app/(frontend)/.well-known/nodeinfo/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(frontend)/.well-known/webfinger/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/.well-known/webfinger">> = Specific
  const handler = {} as typeof import("../../src/app/(frontend)/.well-known/webfinger/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(frontend)/ap/actors/[handle]/followers/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/ap/actors/[handle]/followers">> = Specific
  const handler = {} as typeof import("../../src/app/(frontend)/ap/actors/[handle]/followers/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(frontend)/ap/actors/[handle]/following/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/ap/actors/[handle]/following">> = Specific
  const handler = {} as typeof import("../../src/app/(frontend)/ap/actors/[handle]/following/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(frontend)/ap/actors/[handle]/inbox/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/ap/actors/[handle]/inbox">> = Specific
  const handler = {} as typeof import("../../src/app/(frontend)/ap/actors/[handle]/inbox/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(frontend)/ap/actors/[handle]/outbox/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/ap/actors/[handle]/outbox">> = Specific
  const handler = {} as typeof import("../../src/app/(frontend)/ap/actors/[handle]/outbox/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(frontend)/ap/actors/[handle]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/ap/actors/[handle]">> = Specific
  const handler = {} as typeof import("../../src/app/(frontend)/ap/actors/[handle]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(frontend)/api/admin/audience/command-center/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/audience/command-center">> = Specific
  const handler = {} as typeof import("../../src/app/(frontend)/api/admin/audience/command-center/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(frontend)/api/admin/calendar/schedule/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/calendar/schedule">> = Specific
  const handler = {} as typeof import("../../src/app/(frontend)/api/admin/calendar/schedule/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(frontend)/api/admin/catalog/import/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/catalog/import">> = Specific
  const handler = {} as typeof import("../../src/app/(frontend)/api/admin/catalog/import/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(frontend)/api/admin/catalog/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/catalog">> = Specific
  const handler = {} as typeof import("../../src/app/(frontend)/api/admin/catalog/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(frontend)/api/admin/commerce/affiliate/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/commerce/affiliate">> = Specific
  const handler = {} as typeof import("../../src/app/(frontend)/api/admin/commerce/affiliate/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(frontend)/api/admin/commerce/dashboard/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/commerce/dashboard">> = Specific
  const handler = {} as typeof import("../../src/app/(frontend)/api/admin/commerce/dashboard/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(frontend)/api/admin/commerce/donations/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/commerce/donations">> = Specific
  const handler = {} as typeof import("../../src/app/(frontend)/api/admin/commerce/donations/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(frontend)/api/admin/commerce/receipts/[orderId]/resend/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/commerce/receipts/[orderId]/resend">> = Specific
  const handler = {} as typeof import("../../src/app/(frontend)/api/admin/commerce/receipts/[orderId]/resend/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(frontend)/api/admin/commerce/reconcile/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/commerce/reconcile">> = Specific
  const handler = {} as typeof import("../../src/app/(frontend)/api/admin/commerce/reconcile/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(frontend)/api/admin/commerce/refunds/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/commerce/refunds">> = Specific
  const handler = {} as typeof import("../../src/app/(frontend)/api/admin/commerce/refunds/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(frontend)/api/admin/commerce/subscriptions/grant/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/commerce/subscriptions/grant">> = Specific
  const handler = {} as typeof import("../../src/app/(frontend)/api/admin/commerce/subscriptions/grant/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(frontend)/api/admin/commerce/subscriptions/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/commerce/subscriptions">> = Specific
  const handler = {} as typeof import("../../src/app/(frontend)/api/admin/commerce/subscriptions/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(frontend)/api/admin/discovery/ai-suggestion/accept/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/discovery/ai-suggestion/accept">> = Specific
  const handler = {} as typeof import("../../src/app/(frontend)/api/admin/discovery/ai-suggestion/accept/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(frontend)/api/admin/discovery/audit/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/discovery/audit">> = Specific
  const handler = {} as typeof import("../../src/app/(frontend)/api/admin/discovery/audit/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(frontend)/api/admin/discovery/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/discovery">> = Specific
  const handler = {} as typeof import("../../src/app/(frontend)/api/admin/discovery/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(frontend)/api/admin/indexing/export/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/indexing/export">> = Specific
  const handler = {} as typeof import("../../src/app/(frontend)/api/admin/indexing/export/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(frontend)/api/admin/indexing/search/reconcile/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/indexing/search/reconcile">> = Specific
  const handler = {} as typeof import("../../src/app/(frontend)/api/admin/indexing/search/reconcile/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(frontend)/api/admin/navigation/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/navigation">> = Specific
  const handler = {} as typeof import("../../src/app/(frontend)/api/admin/navigation/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(frontend)/api/admin/notifications/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/notifications">> = Specific
  const handler = {} as typeof import("../../src/app/(frontend)/api/admin/notifications/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(frontend)/api/admin/redirects/export/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/redirects/export">> = Specific
  const handler = {} as typeof import("../../src/app/(frontend)/api/admin/redirects/export/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(frontend)/api/admin/redirects/import/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/redirects/import">> = Specific
  const handler = {} as typeof import("../../src/app/(frontend)/api/admin/redirects/import/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(frontend)/api/admin/redirects/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/redirects">> = Specific
  const handler = {} as typeof import("../../src/app/(frontend)/api/admin/redirects/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(frontend)/api/admin/releases/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/releases/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/(frontend)/api/admin/releases/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(frontend)/api/admin/releases/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/releases">> = Specific
  const handler = {} as typeof import("../../src/app/(frontend)/api/admin/releases/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(frontend)/api/admin/schedule-health/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/schedule-health">> = Specific
  const handler = {} as typeof import("../../src/app/(frontend)/api/admin/schedule-health/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(frontend)/api/admin/social/accounts/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/social/accounts">> = Specific
  const handler = {} as typeof import("../../src/app/(frontend)/api/admin/social/accounts/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(frontend)/api/admin/social/analytics/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/social/analytics">> = Specific
  const handler = {} as typeof import("../../src/app/(frontend)/api/admin/social/analytics/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(frontend)/api/admin/social/dispatch/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/social/dispatch">> = Specific
  const handler = {} as typeof import("../../src/app/(frontend)/api/admin/social/dispatch/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(frontend)/api/admin/social/worker/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/social/worker">> = Specific
  const handler = {} as typeof import("../../src/app/(frontend)/api/admin/social/worker/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(frontend)/api/admin/themes/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/themes">> = Specific
  const handler = {} as typeof import("../../src/app/(frontend)/api/admin/themes/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(frontend)/api/admin/translations/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/translations">> = Specific
  const handler = {} as typeof import("../../src/app/(frontend)/api/admin/translations/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(frontend)/api/admin/webhooks/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/webhooks">> = Specific
  const handler = {} as typeof import("../../src/app/(frontend)/api/admin/webhooks/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(frontend)/api/admin/workflow/actions/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/workflow/actions">> = Specific
  const handler = {} as typeof import("../../src/app/(frontend)/api/admin/workflow/actions/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(frontend)/api/admin/workflow/audit/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/workflow/audit">> = Specific
  const handler = {} as typeof import("../../src/app/(frontend)/api/admin/workflow/audit/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(frontend)/api/admin/workflow/bulk/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/workflow/bulk">> = Specific
  const handler = {} as typeof import("../../src/app/(frontend)/api/admin/workflow/bulk/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(frontend)/api/admin/workflow/command-center/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/workflow/command-center">> = Specific
  const handler = {} as typeof import("../../src/app/(frontend)/api/admin/workflow/command-center/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(frontend)/api/admin/workflow/comments/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/workflow/comments">> = Specific
  const handler = {} as typeof import("../../src/app/(frontend)/api/admin/workflow/comments/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(frontend)/api/admin/workflow/queues/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/workflow/queues">> = Specific
  const handler = {} as typeof import("../../src/app/(frontend)/api/admin/workflow/queues/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(frontend)/api/admin/workflow/templates/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/workflow/templates">> = Specific
  const handler = {} as typeof import("../../src/app/(frontend)/api/admin/workflow/templates/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(frontend)/api/analytics/collect/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/analytics/collect">> = Specific
  const handler = {} as typeof import("../../src/app/(frontend)/api/analytics/collect/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(frontend)/api/analytics/consent/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/analytics/consent">> = Specific
  const handler = {} as typeof import("../../src/app/(frontend)/api/analytics/consent/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(frontend)/api/analytics/report/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/analytics/report">> = Specific
  const handler = {} as typeof import("../../src/app/(frontend)/api/analytics/report/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(frontend)/api/auth/logout/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/logout">> = Specific
  const handler = {} as typeof import("../../src/app/(frontend)/api/auth/logout/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(frontend)/api/auth/passkey/complete/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/passkey/complete">> = Specific
  const handler = {} as typeof import("../../src/app/(frontend)/api/auth/passkey/complete/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(frontend)/api/auth/passkey/options/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/passkey/options">> = Specific
  const handler = {} as typeof import("../../src/app/(frontend)/api/auth/passkey/options/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(frontend)/api/auth/passkeys/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/passkeys">> = Specific
  const handler = {} as typeof import("../../src/app/(frontend)/api/auth/passkeys/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(frontend)/api/calendar/export/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/calendar/export">> = Specific
  const handler = {} as typeof import("../../src/app/(frontend)/api/calendar/export/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(frontend)/api/commerce/affiliate/conversions/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/commerce/affiliate/conversions">> = Specific
  const handler = {} as typeof import("../../src/app/(frontend)/api/commerce/affiliate/conversions/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(frontend)/api/commerce/affiliate/redirect/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/commerce/affiliate/redirect">> = Specific
  const handler = {} as typeof import("../../src/app/(frontend)/api/commerce/affiliate/redirect/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(frontend)/api/commerce/cart/merge/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/commerce/cart/merge">> = Specific
  const handler = {} as typeof import("../../src/app/(frontend)/api/commerce/cart/merge/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(frontend)/api/commerce/cart/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/commerce/cart">> = Specific
  const handler = {} as typeof import("../../src/app/(frontend)/api/commerce/cart/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(frontend)/api/commerce/checkout/initiate/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/commerce/checkout/initiate">> = Specific
  const handler = {} as typeof import("../../src/app/(frontend)/api/commerce/checkout/initiate/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(frontend)/api/commerce/checkout/status/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/commerce/checkout/status">> = Specific
  const handler = {} as typeof import("../../src/app/(frontend)/api/commerce/checkout/status/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(frontend)/api/commerce/checkout/test/confirm/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/commerce/checkout/test/confirm">> = Specific
  const handler = {} as typeof import("../../src/app/(frontend)/api/commerce/checkout/test/confirm/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(frontend)/api/commerce/crypto/verify/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/commerce/crypto/verify">> = Specific
  const handler = {} as typeof import("../../src/app/(frontend)/api/commerce/crypto/verify/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(frontend)/api/commerce/donations/campaign/[campaignId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/commerce/donations/campaign/[campaignId]">> = Specific
  const handler = {} as typeof import("../../src/app/(frontend)/api/commerce/donations/campaign/[campaignId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(frontend)/api/commerce/donations/intent/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/commerce/donations/intent">> = Specific
  const handler = {} as typeof import("../../src/app/(frontend)/api/commerce/donations/intent/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(frontend)/api/commerce/donations/privacy/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/commerce/donations/privacy">> = Specific
  const handler = {} as typeof import("../../src/app/(frontend)/api/commerce/donations/privacy/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(frontend)/api/commerce/download/[grantKey]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/commerce/download/[grantKey]">> = Specific
  const handler = {} as typeof import("../../src/app/(frontend)/api/commerce/download/[grantKey]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(frontend)/api/commerce/proposal/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/commerce/proposal">> = Specific
  const handler = {} as typeof import("../../src/app/(frontend)/api/commerce/proposal/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(frontend)/api/commerce/referrals/claim/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/commerce/referrals/claim">> = Specific
  const handler = {} as typeof import("../../src/app/(frontend)/api/commerce/referrals/claim/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(frontend)/api/commerce/subscriptions/checkout/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/commerce/subscriptions/checkout">> = Specific
  const handler = {} as typeof import("../../src/app/(frontend)/api/commerce/subscriptions/checkout/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(frontend)/api/commerce/subscriptions/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/commerce/subscriptions">> = Specific
  const handler = {} as typeof import("../../src/app/(frontend)/api/commerce/subscriptions/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(frontend)/api/commerce/webhooks/[provider]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/commerce/webhooks/[provider]">> = Specific
  const handler = {} as typeof import("../../src/app/(frontend)/api/commerce/webhooks/[provider]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(frontend)/api/community/blocks/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/community/blocks">> = Specific
  const handler = {} as typeof import("../../src/app/(frontend)/api/community/blocks/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(frontend)/api/community/comments/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/community/comments">> = Specific
  const handler = {} as typeof import("../../src/app/(frontend)/api/community/comments/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(frontend)/api/community/conversations/[conversationId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/community/conversations/[conversationId]">> = Specific
  const handler = {} as typeof import("../../src/app/(frontend)/api/community/conversations/[conversationId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(frontend)/api/community/conversations/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/community/conversations">> = Specific
  const handler = {} as typeof import("../../src/app/(frontend)/api/community/conversations/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(frontend)/api/community/directory/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/community/directory">> = Specific
  const handler = {} as typeof import("../../src/app/(frontend)/api/community/directory/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(frontend)/api/community/history/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/community/history">> = Specific
  const handler = {} as typeof import("../../src/app/(frontend)/api/community/history/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(frontend)/api/community/message-requests/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/community/message-requests">> = Specific
  const handler = {} as typeof import("../../src/app/(frontend)/api/community/message-requests/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(frontend)/api/community/messages/report/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/community/messages/report">> = Specific
  const handler = {} as typeof import("../../src/app/(frontend)/api/community/messages/report/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(frontend)/api/community/messages/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/community/messages">> = Specific
  const handler = {} as typeof import("../../src/app/(frontend)/api/community/messages/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(frontend)/api/community/moderation/appeals/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/community/moderation/appeals">> = Specific
  const handler = {} as typeof import("../../src/app/(frontend)/api/community/moderation/appeals/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(frontend)/api/community/moderation/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/community/moderation">> = Specific
  const handler = {} as typeof import("../../src/app/(frontend)/api/community/moderation/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(frontend)/api/community/notification-preferences/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/community/notification-preferences">> = Specific
  const handler = {} as typeof import("../../src/app/(frontend)/api/community/notification-preferences/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(frontend)/api/community/notifications/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/community/notifications">> = Specific
  const handler = {} as typeof import("../../src/app/(frontend)/api/community/notifications/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(frontend)/api/community/posts/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/community/posts">> = Specific
  const handler = {} as typeof import("../../src/app/(frontend)/api/community/posts/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(frontend)/api/community/profiles/[handle]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/community/profiles/[handle]">> = Specific
  const handler = {} as typeof import("../../src/app/(frontend)/api/community/profiles/[handle]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(frontend)/api/community/reactions/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/community/reactions">> = Specific
  const handler = {} as typeof import("../../src/app/(frontend)/api/community/reactions/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(frontend)/api/community/relationships/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/community/relationships">> = Specific
  const handler = {} as typeof import("../../src/app/(frontend)/api/community/relationships/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(frontend)/api/community/reports/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/community/reports">> = Specific
  const handler = {} as typeof import("../../src/app/(frontend)/api/community/reports/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(frontend)/api/community/threads/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/community/threads">> = Specific
  const handler = {} as typeof import("../../src/app/(frontend)/api/community/threads/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(frontend)/api/email/webhook/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/email/webhook">> = Specific
  const handler = {} as typeof import("../../src/app/(frontend)/api/email/webhook/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(frontend)/api/forms/[formId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/forms/[formId]">> = Specific
  const handler = {} as typeof import("../../src/app/(frontend)/api/forms/[formId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(frontend)/api/foundation-smoke/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/foundation-smoke">> = Specific
  const handler = {} as typeof import("../../src/app/(frontend)/api/foundation-smoke/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(frontend)/api/layouts/[id]/choices/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/layouts/[id]/choices">> = Specific
  const handler = {} as typeof import("../../src/app/(frontend)/api/layouts/[id]/choices/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(frontend)/api/layouts/[id]/rollback/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/layouts/[id]/rollback">> = Specific
  const handler = {} as typeof import("../../src/app/(frontend)/api/layouts/[id]/rollback/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(frontend)/api/layouts/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/layouts/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/(frontend)/api/layouts/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(frontend)/api/layouts/overview/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/layouts/overview">> = Specific
  const handler = {} as typeof import("../../src/app/(frontend)/api/layouts/overview/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(frontend)/api/layouts/patterns/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/layouts/patterns">> = Specific
  const handler = {} as typeof import("../../src/app/(frontend)/api/layouts/patterns/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(frontend)/api/layouts/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/layouts">> = Specific
  const handler = {} as typeof import("../../src/app/(frontend)/api/layouts/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(frontend)/api/layouts/templates/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/layouts/templates">> = Specific
  const handler = {} as typeof import("../../src/app/(frontend)/api/layouts/templates/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(frontend)/api/media/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/media/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/(frontend)/api/media/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(frontend)/api/media/[id]/variants/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/media/[id]/variants">> = Specific
  const handler = {} as typeof import("../../src/app/(frontend)/api/media/[id]/variants/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(frontend)/api/media/attach/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/media/attach">> = Specific
  const handler = {} as typeof import("../../src/app/(frontend)/api/media/attach/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(frontend)/api/media/command-center/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/media/command-center">> = Specific
  const handler = {} as typeof import("../../src/app/(frontend)/api/media/command-center/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(frontend)/api/media/governance/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/media/governance">> = Specific
  const handler = {} as typeof import("../../src/app/(frontend)/api/media/governance/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(frontend)/api/media/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/media">> = Specific
  const handler = {} as typeof import("../../src/app/(frontend)/api/media/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(frontend)/api/media/sessions/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/media/sessions/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/(frontend)/api/media/sessions/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(frontend)/api/media/sessions/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/media/sessions">> = Specific
  const handler = {} as typeof import("../../src/app/(frontend)/api/media/sessions/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(frontend)/api/media/upload/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/media/upload">> = Specific
  const handler = {} as typeof import("../../src/app/(frontend)/api/media/upload/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(frontend)/api/member-auth/deactivate/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/member-auth/deactivate">> = Specific
  const handler = {} as typeof import("../../src/app/(frontend)/api/member-auth/deactivate/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(frontend)/api/member-auth/delete/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/member-auth/delete">> = Specific
  const handler = {} as typeof import("../../src/app/(frontend)/api/member-auth/delete/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(frontend)/api/member-auth/export/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/member-auth/export">> = Specific
  const handler = {} as typeof import("../../src/app/(frontend)/api/member-auth/export/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(frontend)/api/member-auth/link/email/confirm/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/member-auth/link/email/confirm">> = Specific
  const handler = {} as typeof import("../../src/app/(frontend)/api/member-auth/link/email/confirm/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(frontend)/api/member-auth/link/email/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/member-auth/link/email">> = Specific
  const handler = {} as typeof import("../../src/app/(frontend)/api/member-auth/link/email/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(frontend)/api/member-auth/link/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/member-auth/link">> = Specific
  const handler = {} as typeof import("../../src/app/(frontend)/api/member-auth/link/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(frontend)/api/member-auth/logout/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/member-auth/logout">> = Specific
  const handler = {} as typeof import("../../src/app/(frontend)/api/member-auth/logout/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(frontend)/api/member-auth/magic-link/complete/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/member-auth/magic-link/complete">> = Specific
  const handler = {} as typeof import("../../src/app/(frontend)/api/member-auth/magic-link/complete/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(frontend)/api/member-auth/magic-link/request/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/member-auth/magic-link/request">> = Specific
  const handler = {} as typeof import("../../src/app/(frontend)/api/member-auth/magic-link/request/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(frontend)/api/member-auth/me/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/member-auth/me">> = Specific
  const handler = {} as typeof import("../../src/app/(frontend)/api/member-auth/me/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(frontend)/api/member-auth/passkey/login/complete/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/member-auth/passkey/login/complete">> = Specific
  const handler = {} as typeof import("../../src/app/(frontend)/api/member-auth/passkey/login/complete/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(frontend)/api/member-auth/passkey/login/options/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/member-auth/passkey/login/options">> = Specific
  const handler = {} as typeof import("../../src/app/(frontend)/api/member-auth/passkey/login/options/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(frontend)/api/member-auth/passkey/register/complete/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/member-auth/passkey/register/complete">> = Specific
  const handler = {} as typeof import("../../src/app/(frontend)/api/member-auth/passkey/register/complete/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(frontend)/api/member-auth/passkey/register/options/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/member-auth/passkey/register/options">> = Specific
  const handler = {} as typeof import("../../src/app/(frontend)/api/member-auth/passkey/register/options/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(frontend)/api/member-auth/profile-media/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/member-auth/profile-media">> = Specific
  const handler = {} as typeof import("../../src/app/(frontend)/api/member-auth/profile-media/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(frontend)/api/member-auth/profile/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/member-auth/profile">> = Specific
  const handler = {} as typeof import("../../src/app/(frontend)/api/member-auth/profile/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(frontend)/api/member-auth/sessions/[id]/revoke/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/member-auth/sessions/[id]/revoke">> = Specific
  const handler = {} as typeof import("../../src/app/(frontend)/api/member-auth/sessions/[id]/revoke/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(frontend)/api/member-auth/sessions/revoke-all/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/member-auth/sessions/revoke-all">> = Specific
  const handler = {} as typeof import("../../src/app/(frontend)/api/member-auth/sessions/revoke-all/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(frontend)/api/member-auth/sessions/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/member-auth/sessions">> = Specific
  const handler = {} as typeof import("../../src/app/(frontend)/api/member-auth/sessions/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(frontend)/api/member-auth/unlink/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/member-auth/unlink">> = Specific
  const handler = {} as typeof import("../../src/app/(frontend)/api/member-auth/unlink/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(frontend)/api/migration/legacy/activate/[runId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/migration/legacy/activate/[runId]">> = Specific
  const handler = {} as typeof import("../../src/app/(frontend)/api/migration/legacy/activate/[runId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(frontend)/api/migration/legacy/execute/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/migration/legacy/execute">> = Specific
  const handler = {} as typeof import("../../src/app/(frontend)/api/migration/legacy/execute/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(frontend)/api/migration/legacy/inspect/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/migration/legacy/inspect">> = Specific
  const handler = {} as typeof import("../../src/app/(frontend)/api/migration/legacy/inspect/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(frontend)/api/migration/legacy/preflight/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/migration/legacy/preflight">> = Specific
  const handler = {} as typeof import("../../src/app/(frontend)/api/migration/legacy/preflight/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(frontend)/api/migration/legacy/report/[runId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/migration/legacy/report/[runId]">> = Specific
  const handler = {} as typeof import("../../src/app/(frontend)/api/migration/legacy/report/[runId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(frontend)/api/migration/legacy/rollback/[runId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/migration/legacy/rollback/[runId]">> = Specific
  const handler = {} as typeof import("../../src/app/(frontend)/api/migration/legacy/rollback/[runId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(frontend)/api/operations/diagnostics/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/operations/diagnostics">> = Specific
  const handler = {} as typeof import("../../src/app/(frontend)/api/operations/diagnostics/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(frontend)/api/operations/support-bundle/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/operations/support-bundle">> = Specific
  const handler = {} as typeof import("../../src/app/(frontend)/api/operations/support-bundle/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(frontend)/api/presentation/export/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/presentation/export">> = Specific
  const handler = {} as typeof import("../../src/app/(frontend)/api/presentation/export/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(frontend)/api/presentation/import/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/presentation/import">> = Specific
  const handler = {} as typeof import("../../src/app/(frontend)/api/presentation/import/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(frontend)/api/realtime/drafts/[articleId]/checkpoint/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/realtime/drafts/[articleId]/checkpoint">> = Specific
  const handler = {} as typeof import("../../src/app/(frontend)/api/realtime/drafts/[articleId]/checkpoint/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(frontend)/api/realtime/presence/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/realtime/presence">> = Specific
  const handler = {} as typeof import("../../src/app/(frontend)/api/realtime/presence/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(frontend)/api/realtime/stream/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/realtime/stream">> = Specific
  const handler = {} as typeof import("../../src/app/(frontend)/api/realtime/stream/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(frontend)/api/setup/complete/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/setup/complete">> = Specific
  const handler = {} as typeof import("../../src/app/(frontend)/api/setup/complete/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(frontend)/api/setup/options/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/setup/options">> = Specific
  const handler = {} as typeof import("../../src/app/(frontend)/api/setup/options/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(frontend)/api/subscribers/confirm/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/subscribers/confirm">> = Specific
  const handler = {} as typeof import("../../src/app/(frontend)/api/subscribers/confirm/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(frontend)/api/subscribers/preferences/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/subscribers/preferences">> = Specific
  const handler = {} as typeof import("../../src/app/(frontend)/api/subscribers/preferences/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(frontend)/api/subscribers/subscribe/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/subscribers/subscribe">> = Specific
  const handler = {} as typeof import("../../src/app/(frontend)/api/subscribers/subscribe/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(frontend)/api/subscribers/unsubscribe/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/subscribers/unsubscribe">> = Specific
  const handler = {} as typeof import("../../src/app/(frontend)/api/subscribers/unsubscribe/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(frontend)/api/v1/[...segments]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/[...segments]">> = Specific
  const handler = {} as typeof import("../../src/app/(frontend)/api/v1/[...segments]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(frontend)/api/v1/attachments/presign/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/attachments/presign">> = Specific
  const handler = {} as typeof import("../../src/app/(frontend)/api/v1/attachments/presign/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(frontend)/api/v1/moderation/cases/batch/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/moderation/cases/batch">> = Specific
  const handler = {} as typeof import("../../src/app/(frontend)/api/v1/moderation/cases/batch/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(frontend)/api/v1/moderation/cases/export/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/moderation/cases/export">> = Specific
  const handler = {} as typeof import("../../src/app/(frontend)/api/v1/moderation/cases/export/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(frontend)/api/v1/moderation/cases/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/moderation/cases">> = Specific
  const handler = {} as typeof import("../../src/app/(frontend)/api/v1/moderation/cases/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(frontend)/api/v1/notifications/[id]/read/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/notifications/[id]/read">> = Specific
  const handler = {} as typeof import("../../src/app/(frontend)/api/v1/notifications/[id]/read/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(frontend)/api/v1/notifications/mark-all-read/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/notifications/mark-all-read">> = Specific
  const handler = {} as typeof import("../../src/app/(frontend)/api/v1/notifications/mark-all-read/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(frontend)/api/v1/notifications/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/notifications">> = Specific
  const handler = {} as typeof import("../../src/app/(frontend)/api/v1/notifications/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(frontend)/api/v1/notifications/stream/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/notifications/stream">> = Specific
  const handler = {} as typeof import("../../src/app/(frontend)/api/v1/notifications/stream/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(frontend)/api/v1/sites/[site_id]/comments/[comment_id]/reactions/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/sites/[site_id]/comments/[comment_id]/reactions">> = Specific
  const handler = {} as typeof import("../../src/app/(frontend)/api/v1/sites/[site_id]/comments/[comment_id]/reactions/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(frontend)/api/v1/sites/[site_id]/spaces/[space_id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/sites/[site_id]/spaces/[space_id]">> = Specific
  const handler = {} as typeof import("../../src/app/(frontend)/api/v1/sites/[site_id]/spaces/[space_id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(frontend)/api/v1/sites/[site_id]/threads/[thread_id]/comments/[comment_id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/sites/[site_id]/threads/[thread_id]/comments/[comment_id]">> = Specific
  const handler = {} as typeof import("../../src/app/(frontend)/api/v1/sites/[site_id]/threads/[thread_id]/comments/[comment_id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(frontend)/api/v1/sites/[site_id]/threads/[thread_id]/comments/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/sites/[site_id]/threads/[thread_id]/comments">> = Specific
  const handler = {} as typeof import("../../src/app/(frontend)/api/v1/sites/[site_id]/threads/[thread_id]/comments/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(frontend)/api/v1/sites/[site_id]/threads/[thread_id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/sites/[site_id]/threads/[thread_id]">> = Specific
  const handler = {} as typeof import("../../src/app/(frontend)/api/v1/sites/[site_id]/threads/[thread_id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(frontend)/api/v1/sites/[site_id]/threads/[thread_id]/subscriptions/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/sites/[site_id]/threads/[thread_id]/subscriptions">> = Specific
  const handler = {} as typeof import("../../src/app/(frontend)/api/v1/sites/[site_id]/threads/[thread_id]/subscriptions/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(frontend)/api/v1/sites/[site_id]/topics/[topic_id]/read/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/sites/[site_id]/topics/[topic_id]/read">> = Specific
  const handler = {} as typeof import("../../src/app/(frontend)/api/v1/sites/[site_id]/topics/[topic_id]/read/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(frontend)/api/v1/sites/[site_id]/topics/[topic_id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/sites/[site_id]/topics/[topic_id]">> = Specific
  const handler = {} as typeof import("../../src/app/(frontend)/api/v1/sites/[site_id]/topics/[topic_id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(frontend)/api/v1/sites/[site_id]/topics/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/sites/[site_id]/topics">> = Specific
  const handler = {} as typeof import("../../src/app/(frontend)/api/v1/sites/[site_id]/topics/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(frontend)/events/[slug]/ics/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/events/[slug]/ics">> = Specific
  const handler = {} as typeof import("../../src/app/(frontend)/events/[slug]/ics/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(frontend)/events/feed.ics/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/events/feed.ics">> = Specific
  const handler = {} as typeof import("../../src/app/(frontend)/events/feed.ics/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(frontend)/feed.json/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/feed.json">> = Specific
  const handler = {} as typeof import("../../src/app/(frontend)/feed.json/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(frontend)/feed.xml/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/feed.xml">> = Specific
  const handler = {} as typeof import("../../src/app/(frontend)/feed.xml/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(frontend)/feeds/[scope]/[slug]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/feeds/[scope]/[slug]">> = Specific
  const handler = {} as typeof import("../../src/app/(frontend)/feeds/[scope]/[slug]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(frontend)/health/live/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/health/live">> = Specific
  const handler = {} as typeof import("../../src/app/(frontend)/health/live/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(frontend)/health/ready/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/health/ready">> = Specific
  const handler = {} as typeof import("../../src/app/(frontend)/health/ready/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(frontend)/media/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/media/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/(frontend)/media/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(frontend)/nodeinfo/2.1/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/nodeinfo/2.1">> = Specific
  const handler = {} as typeof import("../../src/app/(frontend)/nodeinfo/2.1/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(frontend)/ops/rebuild-notification-counters/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/ops/rebuild-notification-counters">> = Specific
  const handler = {} as typeof import("../../src/app/(frontend)/ops/rebuild-notification-counters/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(frontend)/podcasts/[slug]/feed.xml/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/podcasts/[slug]/feed.xml">> = Specific
  const handler = {} as typeof import("../../src/app/(frontend)/podcasts/[slug]/feed.xml/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(frontend)/podcasts/episodes/[slug]/chapters.json/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/podcasts/episodes/[slug]/chapters.json">> = Specific
  const handler = {} as typeof import("../../src/app/(frontend)/podcasts/episodes/[slug]/chapters.json/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(frontend)/podcasts/episodes/[slug]/transcript/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/podcasts/episodes/[slug]/transcript">> = Specific
  const handler = {} as typeof import("../../src/app/(frontend)/podcasts/episodes/[slug]/transcript/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(frontend)/sitemap.xml/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/sitemap.xml">> = Specific
  const handler = {} as typeof import("../../src/app/(frontend)/sitemap.xml/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(frontend)/sitemaps/[page]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/sitemaps/[page]">> = Specific
  const handler = {} as typeof import("../../src/app/(frontend)/sitemaps/[page]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(frontend)/video-captions/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/video-captions/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/(frontend)/video-captions/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(frontend)/video-media/[id]/[filename]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/video-media/[id]/[filename]">> = Specific
  const handler = {} as typeof import("../../src/app/(frontend)/video-media/[id]/[filename]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(payload)/api/[...slug]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/[...slug]">> = Specific
  const handler = {} as typeof import("../../src/app/(payload)/api/[...slug]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(payload)/api/graphql-playground/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/graphql-playground">> = Specific
  const handler = {} as typeof import("../../src/app/(payload)/api/graphql-playground/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(payload)/api/graphql/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/graphql">> = Specific
  const handler = {} as typeof import("../../src/app/(payload)/api/graphql/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../src/app/(frontend)/guided-setup/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/guided-setup">> = Specific
  const handler = {} as typeof import("../../src/app/(frontend)/guided-setup/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(frontend)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/(frontend)/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(payload)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/(payload)/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
