var R=require("../../../../../chunks/[turbopack]_runtime.js")("server/app/(frontend)/api/community/relationships/route.js")
R.c("server/chunks/[root-of-the-server]__1rz0zcw._.js")
R.c("server/chunks/_0mcj9ym._.js")
R.c("server/chunks/node_modules_next_dist_compiled_06q7exl._.js")
R.c("server/chunks/[root-of-the-server]__0v_wsvf._.js")
R.c("server/chunks/[root-of-the-server]__12uj088._.js")
R.c("server/chunks/_0k60ylq._.js")
R.c("server/chunks/_1ntdu-6._.js")
R.c("server/chunks/node_modules_next_dist_17t41mm._.js")
R.c("server/chunks/_0zvlmmz._.js")
R.c("server/chunks/1oeh_server_app_(frontend)_api_community_relationships_route_actions_0wm17-2.js")
R.m(863190)
module.exports=R.m(863190).exports
