var R=require("../../../chunks/[turbopack]_runtime.js")("server/app/(frontend)/feed.json/route.js")
R.c("server/chunks/[root-of-the-server]__126vd2k._.js")
R.c("server/chunks/[root-of-the-server]__0v_wsvf._.js")
R.c("server/chunks/node_modules_next_dist_compiled_06q7exl._.js")
R.c("server/chunks/node_modules_next_dist_17t41mm._.js")
R.c("server/chunks/_0k60ylq._.js")
R.c("server/chunks/[root-of-the-server]__12uj088._.js")
R.c("server/chunks/_0zvlmmz._.js")
R.c("server/chunks/_1ntdu-6._.js")
R.c("server/chunks/_next-internal_server_app_(frontend)_feed_json_route_actions_0d38o0v.js")
R.m(587772)
module.exports=R.m(587772).exports
