var R=require("../../../../../chunks/[turbopack]_runtime.js")("server/app/(frontend)/api/operations/diagnostics/route.js")
R.c("server/chunks/[root-of-the-server]__00e98ho._.js")
R.c("server/chunks/[root-of-the-server]__0v_wsvf._.js")
R.c("server/chunks/[root-of-the-server]__12uj088._.js")
R.c("server/chunks/_11_6_s4._.js")
R.c("server/chunks/node_modules_next_dist_compiled_06q7exl._.js")
R.c("server/chunks/_1ntdu-6._.js")
R.c("server/chunks/src_migrations_index_ts_0-669_q._.js")
R.c("server/chunks/node_modules_next_dist_17t41mm._.js")
R.c("server/chunks/_0zvlmmz._.js")
R.c("server/chunks/_0847jrf._.js")
R.c("server/chunks/1oeh_server_app_(frontend)_api_operations_diagnostics_route_actions_0er0h4r.js")
R.m(385721)
module.exports=R.m(385721).exports
