var R=require("../../../../../chunks/[turbopack]_runtime.js")("server/app/(frontend)/api/experiences/exposure/route.js")
R.c("server/chunks/[root-of-the-server]__0u2f_6r._.js")
R.c("server/chunks/_0x3rjoa._.js")
R.c("server/chunks/node_modules_next_dist_compiled_06q7exl._.js")
R.c("server/chunks/node_modules_next_dist_0asya_d._.js")
R.c("server/chunks/[root-of-the-server]__0v_wsvf._.js")
R.c("server/chunks/_1ntdu-6._.js")
R.c("server/chunks/node_modules_next_dist_17t41mm._.js")
R.c("server/chunks/[root-of-the-server]__12uj088._.js")
R.c("server/chunks/_0k60ylq._.js")
R.c("server/chunks/_0zvlmmz._.js")
R.c("server/chunks/node_modules_next_1lo724y._.js")
R.c("server/chunks/1oeh_server_app_(frontend)_api_experiences_exposure_route_actions_0ey5aoi.js")
R.m(338437)
module.exports=R.m(338437).exports
