import {
  ActivityEvents,
  AudienceLists,
  AudienceMemberships,
  AudienceSegments,
  AutomationDefinitions,
  ConsentEvents,
  ContactTaggings,
  ContactTags,
  Contacts,
  DealsOrOpportunities,
  DeliveryIdentities,
  DeliveryReceipts,
  DigestDefinitions,
  DigestRuns,
  EmailDeliveries,
  EmailMessages,
  FormDefinitions,
  FormSchemas,
  FormSubmissions,
  InteractionRecords,
  NextActions,
  NotificationChannels,
  NotificationPreferences,
  Notifications,
  Organizations,
  OwnerAssignments,
  Preferences,
  RelationshipNotes,
  RelationshipRecords,
  SubscriberConfirmationTokens,
  Subscribers,
  SubmissionAttachments,
  Suppressions,
  WorkflowItems,
} from '../../collections/Audience'
import type { DomainDefinition } from '../core/payload-domains'
import { audienceTasks } from './tasks'

export const audienceDomain: DomainDefinition = {
  id: 'audience',
  collections: [
    FormDefinitions,
    FormSchemas,
    FormSubmissions,
    SubmissionAttachments,
    Contacts,
    Organizations,
    RelationshipRecords,
    ContactTags,
    ContactTaggings,
    InteractionRecords,
    RelationshipNotes,
    DealsOrOpportunities,
    OwnerAssignments,
    NextActions,
    WorkflowItems,
    AudienceLists,
    AudienceSegments,
    AudienceMemberships,
    SubscriberConfirmationTokens,
    Subscribers,
    ConsentEvents,
    Preferences,
    Suppressions,
    EmailMessages,
    DeliveryIdentities,
    EmailDeliveries,
    ActivityEvents,
    Notifications,
    NotificationPreferences,
    NotificationChannels,
    DigestDefinitions,
    DigestRuns,
    DeliveryReceipts,
    AutomationDefinitions,
  ],
  tasks: audienceTasks,
}
