var R=require("../../../../../chunks/[turbopack]_runtime.js")("server/app/(frontend)/api/subscribers/preferences/route.js")
R.c("server/chunks/[root-of-the-server]__06ke62v._.js")
R.c("server/chunks/[root-of-the-server]__0v_wsvf._.js")
R.c("server/chunks/node_modules_next_dist_compiled_06q7exl._.js")
R.c("server/chunks/_0zvlmmz._.js")
R.c("server/chunks/node_modules_next_dist_17t41mm._.js")
R.c("server/chunks/_19f7vkx._.js")
R.c("server/chunks/[root-of-the-server]__12uj088._.js")
R.c("server/chunks/_0x_7-la._.js")
R.c("server/chunks/1oeh_server_app_(frontend)_api_subscribers_preferences_route_actions_06rqml8.js")
R.m(435254)
module.exports=R.m(435254).exports
