var R=require("../../../../../chunks/[turbopack]_runtime.js")("server/app/(frontend)/api/realtime/stream/route.js")
R.c("server/chunks/[root-of-the-server]__1wu4no3._.js")
R.c("server/chunks/_0rkuwbn._.js")
R.c("server/chunks/node_modules_next_dist_compiled_06q7exl._.js")
R.c("server/chunks/[root-of-the-server]__0v_wsvf._.js")
R.c("server/chunks/[root-of-the-server]__12uj088._.js")
R.c("server/chunks/_0k60ylq._.js")
R.c("server/chunks/_1ntdu-6._.js")
R.c("server/chunks/node_modules_next_dist_17t41mm._.js")
R.c("server/chunks/_0zvlmmz._.js")
R.c("server/chunks/_next-internal_server_app_(frontend)_api_realtime_stream_route_actions_0r05sip.js")
R.m(508958)
module.exports=R.m(508958).exports
