var R=require("../../../../../../../chunks/[turbopack]_runtime.js")("server/app/(frontend)/api/v1/moderation/cases/batch/route.js")
R.c("server/chunks/[root-of-the-server]__0mh5nlt._.js")
R.c("server/chunks/[root-of-the-server]__0v_wsvf._.js")
R.c("server/chunks/node_modules_next_dist_compiled_06q7exl._.js")
R.c("server/chunks/node_modules_next_dist_17t41mm._.js")
R.c("server/chunks/_0847jrf._.js")
R.c("server/chunks/[root-of-the-server]__12uj088._.js")
R.c("server/chunks/_0zvlmmz._.js")
R.c("server/chunks/_1ntdu-6._.js")
R.c("server/chunks/1oeh_server_app_(frontend)_api_v1_moderation_cases_batch_route_actions_0v_lwah.js")
R.m(387449)
module.exports=R.m(387449).exports
