var R=require("../../../../../../../chunks/[turbopack]_runtime.js")("server/app/(frontend)/api/v1/notifications/[id]/read/route.js")
R.c("server/chunks/[root-of-the-server]__1_0nha1._.js")
R.c("server/chunks/[root-of-the-server]__0v_wsvf._.js")
R.c("server/chunks/node_modules_next_dist_compiled_06q7exl._.js")
R.c("server/chunks/_1j0_hlv._.js")
R.c("server/chunks/[root-of-the-server]__12uj088._.js")
R.c("server/chunks/_0k60ylq._.js")
R.c("server/chunks/_1ntdu-6._.js")
R.c("server/chunks/node_modules_next_dist_17t41mm._.js")
R.c("server/chunks/_0zvlmmz._.js")
R.c("server/chunks/1oeh_server_app_(frontend)_api_v1_notifications_[id]_read_route_actions_043-bbm.js")
R.m(478799)
module.exports=R.m(478799).exports
