var R=require("../../../../../chunks/[turbopack]_runtime.js")("server/app/(frontend)/api/auth/passkeys/route.js")
R.c("server/chunks/[root-of-the-server]__095n9qt._.js")
R.c("server/chunks/src_modules_operations_08ru58e._.js")
R.c("server/chunks/node_modules_next_dist_compiled_06q7exl._.js")
R.c("server/chunks/_1ntdu-6._.js")
R.c("server/chunks/[root-of-the-server]__0v_wsvf._.js")
R.c("server/chunks/src_modules_starters_1hr9_s6._.js")
R.c("server/chunks/node_modules_next_dist_17t41mm._.js")
R.c("server/chunks/_0k60ylq._.js")
R.c("server/chunks/node_modules_1f2ccrm._.js")
R.c("server/chunks/[root-of-the-server]__12uj088._.js")
R.c("server/chunks/_0zvlmmz._.js")
R.c("server/chunks/_next-internal_server_app_(frontend)_api_auth_passkeys_route_actions_18ihvel.js")
R.m(23135)
module.exports=R.m(23135).exports
