var R=require("../../../../../../chunks/[turbopack]_runtime.js")("server/app/(frontend)/api/admin/intelligence/editorial-review/route.js")
R.c("server/chunks/[root-of-the-server]__1ezs9co._.js")
R.c("server/chunks/[root-of-the-server]__0v_wsvf._.js")
R.c("server/chunks/node_modules_next_dist_compiled_06q7exl._.js")
R.c("server/chunks/_16slbpt._.js")
R.c("server/chunks/node_modules_next_1lo724y._.js")
R.c("server/chunks/[root-of-the-server]__12uj088._.js")
R.c("server/chunks/_0zvlmmz._.js")
R.c("server/chunks/node_modules_next_dist_17t41mm._.js")
R.c("server/chunks/_0x_7-la._.js")
R.c("server/chunks/_19f7vkx._.js")
R.c("server/chunks/node_modules_next_dist_0asya_d._.js")
R.c("server/chunks/1jng_app_(frontend)_api_admin_intelligence_editorial-review_route_actions_0invzv4.js")
R.m(233382)
module.exports=R.m(233382).exports
