var R=require("../../../../../../chunks/[turbopack]_runtime.js")("server/app/(frontend)/api/commerce/affiliate/redirect/route.js")
R.c("server/chunks/_03ppfi9._.js")
R.c("server/chunks/node_modules_next_dist_0asya_d._.js")
R.c("server/chunks/[root-of-the-server]__0hco37z._.js")
R.c("server/chunks/node_modules_next_dist_17t41mm._.js")
R.c("server/chunks/[root-of-the-server]__12uj088._.js")
R.c("server/chunks/node_modules_next_dist_compiled_06q7exl._.js")
R.c("server/chunks/node_modules_next_1lo724y._.js")
R.c("server/chunks/1oeh_server_app_(frontend)_api_commerce_affiliate_redirect_route_actions_0p88uoo.js")
R.m(864957)
module.exports=R.m(864957).exports
