var R=require("../../../../../../chunks/[turbopack]_runtime.js")("server/app/(frontend)/api/admin/workflow/audit/route.js")
R.c("server/chunks/src_modules_editorial_1f78hdp._.js")
R.c("server/chunks/[root-of-the-server]__1x7b26x._.js")
R.c("server/chunks/node_modules_next_1lo724y._.js")
R.c("server/chunks/[root-of-the-server]__12uj088._.js")
R.c("server/chunks/[root-of-the-server]__0v_wsvf._.js")
R.c("server/chunks/node_modules_next_dist_17t41mm._.js")
R.c("server/chunks/node_modules_next_dist_0asya_d._.js")
R.c("server/chunks/_0847jrf._.js")
R.c("server/chunks/_1ntdu-6._.js")
R.c("server/chunks/_0zvlmmz._.js")
R.c("server/chunks/node_modules_next_dist_compiled_06q7exl._.js")
R.c("server/chunks/1oeh_server_app_(frontend)_api_admin_workflow_audit_route_actions_1x11jg2.js")
R.m(871344)
module.exports=R.m(871344).exports
