var R=require("../../../../../../../../../chunks/[turbopack]_runtime.js")("server/app/(frontend)/api/v1/sites/[site_id]/threads/[thread_id]/subscriptions/route.js")
R.c("server/chunks/[root-of-the-server]__05o358a._.js")
R.c("server/chunks/[root-of-the-server]__0v_wsvf._.js")
R.c("server/chunks/node_modules_next_dist_compiled_06q7exl._.js")
R.c("server/chunks/_1_azacj._.js")
R.c("server/chunks/node_modules_next_dist_17t41mm._.js")
R.c("server/chunks/_0k60ylq._.js")
R.c("server/chunks/[root-of-the-server]__12uj088._.js")
R.c("server/chunks/_1ntdu-6._.js")
R.c("server/chunks/_0zvlmmz._.js")
R.c("server/chunks/21a9_api_v1_sites_[site_id]_threads_[thread_id]_subscriptions_route_actions_0n31eou.js")
R.m(69941)
module.exports=R.m(69941).exports
