import {
  Albums,
  ArticleFamilyContent,
  Categories,
  Content,
  Events,
  MarkdownConversionReports,
  MediaAssets,
  MediaUsages,
  PreviewTokens,
  PublicRedirects,
  RevisionRecords,
  ScheduledPublishJobs,
  Sections,
  Series,
  Sources,
  Tags,
  TaxonomyRedirects,
  TimelineMemberships,
  Timelines,
  Topics,
} from '../../collections/Publishing'
import {
  CalendarEntries,
  DiscussionPosts,
  Discussions,
  Forums,
  ForumSections,
} from '../../collections/Community'
import type { DomainDefinition } from '../core/payload-domains'
import { editorialTasks } from './tasks'

export const editorialDomain: DomainDefinition = {
  id: 'editorial',
  collections: [
    MediaAssets,
    Sections,
    Categories,
    Topics,
    Tags,
    Series,
    TaxonomyRedirects,
    PublicRedirects,
    Content,
    ArticleFamilyContent,
    MarkdownConversionReports,
    RevisionRecords,
    PreviewTokens,
    ScheduledPublishJobs,
    Events,
    Timelines,
    TimelineMemberships,
    Sources,
    Albums,
    MediaUsages,
    ForumSections,
    Forums,
    Discussions,
    DiscussionPosts,
    CalendarEntries,
  ],
  tasks: editorialTasks,
}
