var R=require("../../../../../chunks/[turbopack]_runtime.js")("server/app/(frontend)/api/admin/starters/route.js")
R.c("server/chunks/[root-of-the-server]__0ru4wgr._.js")
R.c("server/chunks/node_modules_next_1lo724y._.js")
R.c("server/chunks/_1h6cdyf._.js")
R.c("server/chunks/node_modules_next_0vctw-h._.js")
R.c("server/chunks/node_modules_next_dist_0asya_d._.js")
R.c("server/chunks/[root-of-the-server]__0v_wsvf._.js")
R.c("server/chunks/src_modules_starters_1hr9_s6._.js")
R.c("server/chunks/_1ntdu-6._.js")
R.c("server/chunks/[root-of-the-server]__12uj088._.js")
R.c("server/chunks/_0zvlmmz._.js")
R.c("server/chunks/_0k60ylq._.js")
R.c("server/chunks/node_modules_next_dist_17t41mm._.js")
R.c("server/chunks/node_modules_next_dist_compiled_06q7exl._.js")
R.c("server/chunks/_next-internal_server_app_(frontend)_api_admin_starters_route_actions_0z9tz_o.js")
R.m(769411)
module.exports=R.m(769411).exports
