var R=require("../../../../../../chunks/[turbopack]_runtime.js")("server/app/(frontend)/api/community/conversations/[conversationId]/route.js")
R.c("server/chunks/[root-of-the-server]__1ghn6jo._.js")
R.c("server/chunks/[root-of-the-server]__0v_wsvf._.js")
R.c("server/chunks/node_modules_next_dist_compiled_06q7exl._.js")
R.c("server/chunks/node_modules_next_dist_17t41mm._.js")
R.c("server/chunks/_0847jrf._.js")
R.c("server/chunks/[root-of-the-server]__12uj088._.js")
R.c("server/chunks/_0zvlmmz._.js")
R.c("server/chunks/_1ntdu-6._.js")
R.c("server/chunks/0ivl_(frontend)_api_community_conversations_[conversationId]_route_actions_1hnxx5h.js")
R.m(185237)
module.exports=R.m(185237).exports
