var R=require("../../chunks/[turbopack]_runtime.js")("server/app/robots.txt/route.js")
R.c("server/chunks/[root-of-the-server]__16d1opy._.js")
R.c("server/chunks/_02ng3hv._.js")
R.c("server/chunks/_0zvlmmz._.js")
R.c("server/chunks/node_modules_next_dist_compiled_06q7exl._.js")
R.c("server/chunks/[root-of-the-server]__0v_wsvf._.js")
R.c("server/chunks/node_modules_next_dist_17t41mm._.js")
R.c("server/chunks/_1ntdu-6._.js")
R.c("server/chunks/[root-of-the-server]__12uj088._.js")
R.c("server/chunks/_0k60ylq._.js")
R.c("server/chunks/node_modules_next_dist_0asya_d._.js")
R.c("server/chunks/node_modules_next_1lo724y._.js")
R.c("server/chunks/_next-internal_server_app_robots_txt_route_actions_15vc_89.js")
R.m(977067)
module.exports=R.m(977067).exports
