var R=require("../../../../../../../chunks/[turbopack]_runtime.js")("server/app/(frontend)/api/migration/legacy/report/[runId]/route.js")
R.c("server/chunks/[root-of-the-server]__0nb5a0q._.js")
R.c("server/chunks/[root-of-the-server]__0v_wsvf._.js")
R.c("server/chunks/node_modules_next_dist_0asya_d._.js")
R.c("server/chunks/node_modules_next_dist_17t41mm._.js")
R.c("server/chunks/node_modules_next_1lo724y._.js")
R.c("server/chunks/node_modules_next_dist_compiled_06q7exl._.js")
R.c("server/chunks/src_modules_portability_legacy-migration_13krzjx._.js")
R.c("server/chunks/_0847jrf._.js")
R.c("server/chunks/_1ntdu-6._.js")
R.c("server/chunks/[root-of-the-server]__12uj088._.js")
R.c("server/chunks/_0zvlmmz._.js")
R.c("server/chunks/1oeh_server_app_(frontend)_api_migration_legacy_report_[runId]_route_actions_00x6vcn.js")
R.m(969234)
module.exports=R.m(969234).exports
