import {
  Carts,
  CatalogImportRuns,
  CheckoutProposals,
  CheckoutSessions,
  CommerceDisputes,
  CommerceRefunds,
  CommerceReconciliationCases,
  DigitalDeliveryGrants,
  DonationCampaigns,
  DonationEvents,
  DonationIntents,
  Donations,
  DigitalDownloadEvents,
  Entitlements,
  InventoryReservations,
  MerchantConnections,
  Orders,
  PaymentIntents,
  PaymentAttempts,
  PaymentMethodCapabilities,
  PaymentWebhookEvents,
  Products,
  Promotions,
  Supporters,
  PlanRevisions,
  Subscriptions,
  SubscriptionEvents,
  PodConnections,
  PodJobs,
  ManualFulfillmentPackages,
} from '../../collections/Commerce'
import type { DomainDefinition } from '../core/payload-domains'
import { commerceTasks } from './tasks'

export const commerceDomain: DomainDefinition = {
  id: 'commerce',
  collections: [
    MerchantConnections,
    PaymentMethodCapabilities,
    Products,
    DigitalDeliveryGrants,
    DigitalDownloadEvents,
    CatalogImportRuns,
    Carts,
    Promotions,
    CheckoutProposals,
    InventoryReservations,
    CheckoutSessions,
    PaymentIntents,
    PaymentAttempts,
    Orders,
    PaymentWebhookEvents,
    CommerceRefunds,
    CommerceDisputes,
    CommerceReconciliationCases,
    Supporters,
    Entitlements,
    PlanRevisions,
    Subscriptions,
    SubscriptionEvents,
    DonationCampaigns,
    DonationIntents,
    Donations,
    DonationEvents,
    PodConnections,
    PodJobs,
    ManualFulfillmentPackages,
  ],
  tasks: commerceTasks,
}
