var R=require("../../../../../../../../../chunks/[turbopack]_runtime.js")("server/app/(frontend)/api/v1/sites/[site_id]/topics/[topic_id]/read/route.js")
R.c("server/chunks/[root-of-the-server]__1qdsezo._.js")
R.c("server/chunks/_108hb9v._.js")
R.c("server/chunks/node_modules_next_dist_compiled_06q7exl._.js")
R.c("server/chunks/[root-of-the-server]__0v_wsvf._.js")
R.c("server/chunks/[root-of-the-server]__12uj088._.js")
R.c("server/chunks/_0k60ylq._.js")
R.c("server/chunks/_1ntdu-6._.js")
R.c("server/chunks/node_modules_next_dist_17t41mm._.js")
R.c("server/chunks/_0zvlmmz._.js")
R.c("server/chunks/0ivl_(frontend)_api_v1_sites_[site_id]_topics_[topic_id]_read_route_actions_0xb3jv7.js")
R.m(170619)
module.exports=R.m(170619).exports
