var R=require("../../../../../../../chunks/[turbopack]_runtime.js")("server/app/(frontend)/api/admin/discovery/ai-suggestion/accept/route.js")
R.c("server/chunks/[root-of-the-server]__1k2tw_1._.js")
R.c("server/chunks/_1knw9dh._.js")
R.c("server/chunks/node_modules_next_dist_0asya_d._.js")
R.c("server/chunks/node_modules_next_dist_compiled_06q7exl._.js")
R.c("server/chunks/[root-of-the-server]__0v_wsvf._.js")
R.c("server/chunks/_0x_7-la._.js")
R.c("server/chunks/node_modules_next_dist_17t41mm._.js")
R.c("server/chunks/_19f7vkx._.js")
R.c("server/chunks/_0zvlmmz._.js")
R.c("server/chunks/[root-of-the-server]__12uj088._.js")
R.c("server/chunks/node_modules_next_1lo724y._.js")
R.c("server/chunks/1jng_app_(frontend)_api_admin_discovery_ai-suggestion_accept_route_actions_18jta79.js")
R.m(65977)
module.exports=R.m(65977).exports
