var R=require("../../../../../../chunks/[turbopack]_runtime.js")("server/app/(frontend)/api/member-auth/magic-link/complete/route.js")
R.c("server/chunks/[root-of-the-server]__1hp7cvu._.js")
R.c("server/chunks/[root-of-the-server]__0v_wsvf._.js")
R.c("server/chunks/node_modules_next_dist_compiled_06q7exl._.js")
R.c("server/chunks/node_modules_next_dist_17t41mm._.js")
R.c("server/chunks/_0k60ylq._.js")
R.c("server/chunks/[root-of-the-server]__12uj088._.js")
R.c("server/chunks/_0zvlmmz._.js")
R.c("server/chunks/_1ntdu-6._.js")
R.c("server/chunks/1oeh_server_app_(frontend)_api_member-auth_magic-link_complete_route_actions_0hdheg2.js")
R.m(446135)
module.exports=R.m(446135).exports
