var R=require("../../../../../chunks/[turbopack]_runtime.js")("server/app/(frontend)/api/member-auth/profile-media/route.js")
R.c("server/chunks/[root-of-the-server]__0-puto-._.js")
R.c("server/chunks/[root-of-the-server]__0v_wsvf._.js")
R.c("server/chunks/node_modules_next_dist_compiled_06q7exl._.js")
R.c("server/chunks/_12cl9tc._.js")
R.c("server/chunks/[root-of-the-server]__12uj088._.js")
R.c("server/chunks/_0k60ylq._.js")
R.c("server/chunks/_1ntdu-6._.js")
R.c("server/chunks/node_modules_next_dist_17t41mm._.js")
R.c("server/chunks/_0zvlmmz._.js")
R.c("server/chunks/1oeh_server_app_(frontend)_api_member-auth_profile-media_route_actions_08v0lg9.js")
R.m(850092)
module.exports=R.m(850092).exports
