var R=require("../../../../../chunks/[turbopack]_runtime.js")("server/app/(frontend)/api/commerce/proposal/route.js")
R.c("server/chunks/[root-of-the-server]__16u1fqu._.js")
R.c("server/chunks/[root-of-the-server]__0v_wsvf._.js")
R.c("server/chunks/src_modules_commerce_cart_ts_0_szfjx._.js")
R.c("server/chunks/node_modules_next_dist_0asya_d._.js")
R.c("server/chunks/node_modules_next_1lo724y._.js")
R.c("server/chunks/node_modules_next_dist_compiled_06q7exl._.js")
R.c("server/chunks/[root-of-the-server]__12uj088._.js")
R.c("server/chunks/_0zvlmmz._.js")
R.c("server/chunks/_1ntdu-6._.js")
R.c("server/chunks/_0k60ylq._.js")
R.c("server/chunks/_04sy5t6._.js")
R.c("server/chunks/node_modules_next_dist_17t41mm._.js")
R.c("server/chunks/_next-internal_server_app_(frontend)_api_commerce_proposal_route_actions_1oa69jq.js")
R.m(687814)
module.exports=R.m(687814).exports
