var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/(frontend)/.well-known/webfinger/route.js")
R.c("server/chunks/[root-of-the-server]__0xs99t7._.js")
R.c("server/chunks/[root-of-the-server]__0v_wsvf._.js")
R.c("server/chunks/node_modules_next_dist_compiled_06q7exl._.js")
R.c("server/chunks/node_modules_next_dist_17t41mm._.js")
R.c("server/chunks/_0847jrf._.js")
R.c("server/chunks/[root-of-the-server]__12uj088._.js")
R.c("server/chunks/_0zvlmmz._.js")
R.c("server/chunks/_1ntdu-6._.js")
R.c("server/chunks/_next-internal_server_app_(frontend)__well-known_webfinger_route_actions_18_y1go.js")
R.m(609596)
module.exports=R.m(609596).exports
