var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/(frontend)/events/feed.ics/route.js")
R.c("server/chunks/[root-of-the-server]__082tmj-._.js")
R.c("server/chunks/_1f0z-3f._.js")
R.c("server/chunks/node_modules_next_dist_compiled_06q7exl._.js")
R.c("server/chunks/[root-of-the-server]__0v_wsvf._.js")
R.c("server/chunks/_1ntdu-6._.js")
R.c("server/chunks/_0847jrf._.js")
R.c("server/chunks/[root-of-the-server]__12uj088._.js")
R.c("server/chunks/node_modules_next_dist_17t41mm._.js")
R.c("server/chunks/_0zvlmmz._.js")
R.c("server/chunks/_next-internal_server_app_(frontend)_events_feed_ics_route_actions_19odeee.js")
R.m(898077)
module.exports=R.m(898077).exports
