import {
  BookChapters,
  BookEditions,
  BookParts,
  Books,
  EditSessions,
  GraphicDocuments,
  Interviews,
  Livestreams,
  MediaDerivatives,
  MediaJobs,
  PodcastEpisodes,
  PodcastSeasons,
  PodcastShows,
  QuickCaptureDrafts,
  TranscriptRevisions,
  TtsOutputs,
  VideoChannels,
  VideoPlaylists,
  Videos,
} from '../../collections/MediaPublishing'
import type { DomainDefinition } from '../core/payload-domains'
import { mediaTasks } from './tasks'

export const mediaDomain: DomainDefinition = {
  id: 'media',
  collections: [
    Books,
    BookParts,
    BookChapters,
    BookEditions,
    PodcastShows,
    PodcastSeasons,
    PodcastEpisodes,
    VideoChannels,
    VideoPlaylists,
    Videos,
    Interviews,
    Livestreams,
    TranscriptRevisions,
    MediaJobs,
    TtsOutputs,
    GraphicDocuments,
    MediaDerivatives,
    EditSessions,
    QuickCaptureDrafts,
  ],
  tasks: mediaTasks,
}
