var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/(payload)/api/graphql-playground/route.js")
R.c("server/chunks/[root-of-the-server]__07kpuka._.js")
R.c("server/chunks/[root-of-the-server]__0v_wsvf._.js")
R.c("server/chunks/[root-of-the-server]__12uj088._.js")
R.c("server/chunks/node_modules_next_dist_compiled_06q7exl._.js")
R.c("server/chunks/node_modules_next_dist_17t41mm._.js")
R.c("server/chunks/_1ntdu-6._.js")
R.c("server/chunks/_0k60ylq._.js")
R.c("server/chunks/_0zvlmmz._.js")
R.c("server/chunks/_1yisj71._.js")
R.c("server/chunks/_next-internal_server_app_(payload)_api_graphql-playground_route_actions_0xg809-.js")
R.m(909633)
module.exports=R.m(909633).exports
