var R=require("../../../../../../../chunks/[turbopack]_runtime.js")("server/app/(frontend)/api/admin/ai/proposals/[id]/route.js")
R.c("server/chunks/[root-of-the-server]__1f6n6qp._.js")
R.c("server/chunks/[root-of-the-server]__0v_wsvf._.js")
R.c("server/chunks/_0id1d50._.js")
R.c("server/chunks/node_modules_next_dist_0asya_d._.js")
R.c("server/chunks/node_modules_next_1lo724y._.js")
R.c("server/chunks/src_modules_ai_0ia2qo5._.js")
R.c("server/chunks/node_modules_next_dist_17t41mm._.js")
R.c("server/chunks/_0x_7-la._.js")
R.c("server/chunks/[root-of-the-server]__12uj088._.js")
R.c("server/chunks/_19f7vkx._.js")
R.c("server/chunks/_0zvlmmz._.js")
R.c("server/chunks/node_modules_next_dist_compiled_06q7exl._.js")
R.c("server/chunks/1oeh_server_app_(frontend)_api_admin_ai_proposals_[id]_route_actions_0ymu0s4.js")
R.m(988032)
module.exports=R.m(988032).exports
