var R=require("../../../../../chunks/[turbopack]_runtime.js")("server/app/(frontend)/api/subscribers/unsubscribe/route.js")
R.c("server/chunks/[root-of-the-server]__03n5dey._.js")
R.c("server/chunks/[root-of-the-server]__0v_wsvf._.js")
R.c("server/chunks/node_modules_next_dist_compiled_06q7exl._.js")
R.c("server/chunks/node_modules_next_dist_17t41mm._.js")
R.c("server/chunks/_0k60ylq._.js")
R.c("server/chunks/[root-of-the-server]__12uj088._.js")
R.c("server/chunks/_0zvlmmz._.js")
R.c("server/chunks/_1ntdu-6._.js")
R.c("server/chunks/1oeh_server_app_(frontend)_api_subscribers_unsubscribe_route_actions_0o4xzqz.js")
R.m(927826)
module.exports=R.m(927826).exports
