var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/(payload)/api/[...slug]/route.js")
R.c("server/chunks/[root-of-the-server]__0rtb4hz._.js")
R.c("server/chunks/[root-of-the-server]__0v_wsvf._.js")
R.c("server/chunks/[root-of-the-server]__12uj088._.js")
R.c("server/chunks/node_modules_next_dist_compiled_06q7exl._.js")
R.c("server/chunks/node_modules_0l-0s3b._.js")
R.c("server/chunks/_1ntdu-6._.js")
R.c("server/chunks/_0k60ylq._.js")
R.c("server/chunks/_0_cd-fp._.js")
R.c("server/chunks/_0zvlmmz._.js")
R.c("server/chunks/node_modules_next_dist_17t41mm._.js")
R.c("server/chunks/_next-internal_server_app_(payload)_api_[___slug]_route_actions_0r6j1is.js")
R.m(447431)
module.exports=R.m(447431).exports
