var R=require("../../../../../../../../chunks/[turbopack]_runtime.js")("server/app/(frontend)/api/v1/sites/[site_id]/topics/[topic_id]/route.js")
R.c("server/chunks/[root-of-the-server]__0hs-kpv._.js")
R.c("server/chunks/[root-of-the-server]__0v_wsvf._.js")
R.c("server/chunks/node_modules_next_dist_compiled_06q7exl._.js")
R.c("server/chunks/_0edqykz._.js")
R.c("server/chunks/[root-of-the-server]__12uj088._.js")
R.c("server/chunks/_1ntdu-6._.js")
R.c("server/chunks/_0847jrf._.js")
R.c("server/chunks/node_modules_next_dist_17t41mm._.js")
R.c("server/chunks/_0zvlmmz._.js")
R.c("server/chunks/1jng_app_(frontend)_api_v1_sites_[site_id]_topics_[topic_id]_route_actions_1efjg92.js")
R.m(621682)
module.exports=R.m(621682).exports
