var R=require("../../../../../../../chunks/[turbopack]_runtime.js")("server/app/(frontend)/api/member-auth/passkey/register/options/route.js")
R.c("server/chunks/[root-of-the-server]__0vlbg2-._.js")
R.c("server/chunks/[root-of-the-server]__0v_wsvf._.js")
R.c("server/chunks/[root-of-the-server]__12uj088._.js")
R.c("server/chunks/node_modules_next_dist_compiled_06q7exl._.js")
R.c("server/chunks/_19gvf21._.js")
R.c("server/chunks/_1ntdu-6._.js")
R.c("server/chunks/node_modules_1f2ccrm._.js")
R.c("server/chunks/node_modules_next_dist_17t41mm._.js")
R.c("server/chunks/_0zvlmmz._.js")
R.c("server/chunks/_0k60ylq._.js")
R.c("server/chunks/1jng_app_(frontend)_api_member-auth_passkey_register_options_route_actions_1jd-9gu.js")
R.m(415208)
module.exports=R.m(415208).exports
