var R=require("../../../../../chunks/[turbopack]_runtime.js")("server/app/(frontend)/api/setup/readiness/route.js")
R.c("server/chunks/[root-of-the-server]__0qn6y2a._.js")
R.c("server/chunks/src_modules_operations_08ru58e._.js")
R.c("server/chunks/_03i4fq0._.js")
R.c("server/chunks/src_modules_starters_1hr9_s6._.js")
R.c("server/chunks/_0zvlmmz._.js")
R.c("server/chunks/[root-of-the-server]__0v_wsvf._.js")
R.c("server/chunks/_0x_7-la._.js")
R.c("server/chunks/node_modules_next_dist_17t41mm._.js")
R.c("server/chunks/node_modules_1f2ccrm._.js")
R.c("server/chunks/[root-of-the-server]__12uj088._.js")
R.c("server/chunks/src_migrations_index_ts_0-669_q._.js")
R.c("server/chunks/_19f7vkx._.js")
R.c("server/chunks/node_modules_next_dist_compiled_06q7exl._.js")
R.c("server/chunks/_next-internal_server_app_(frontend)_api_setup_readiness_route_actions_1jjt1a8.js")
R.m(64240)
module.exports=R.m(64240).exports
